services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/srv/node/app # Mount local directory to container
    ports:
      - "9229:9229"
      #  - "3000:3000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./html:/usr/share/nginx/html:ro
      - ./static:/usr/share/nginx/static:ro
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
